replicas: 1

config:
  DEBUG: "true"
  
  DB_HOST: postgres.demo-system.svc.cluster.local
  DB_PORT: "5432"
  DB_USER: test
  DB_PASS: test
  DB_NAME: testdb
  DB_PARAMS: "sslmode=disable"

  NAMESPACES: "krateo-system"


resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 128Mi
